export const API = "http://localhost:3001/";
export const SPOT_BASE = "https://api.spotify.com/v1/";
export const TEST_RESPONSE = {
  tracks: {
    href: "https://api.spotify.com/v1/search?query=werewolf&type=track&offset=0&limit=10",
    items: [
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/6MwPCCR936cYfM1dLsGVnl",
              },
              href: "https://api.spotify.com/v1/artists/6MwPCCR936cYfM1dLsGVnl",
              id: "6MwPCCR936cYfM1dLsGVnl",
              name: "Motionless In White",
              type: "artist",
              uri: "spotify:artist:6MwPCCR936cYfM1dLsGVnl",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/0DoVnWjNFYoUfq7qe36jxh",
          },
          href: "https://api.spotify.com/v1/albums/0DoVnWjNFYoUfq7qe36jxh",
          id: "0DoVnWjNFYoUfq7qe36jxh",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2733528a891d36d16d760cda271",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e023528a891d36d16d760cda271",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048513528a891d36d16d760cda271",
              width: 64,
            },
          ],
          name: "Scoring The End Of The World",
          release_date: "2022-06-10",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:0DoVnWjNFYoUfq7qe36jxh",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6MwPCCR936cYfM1dLsGVnl",
            },
            href: "https://api.spotify.com/v1/artists/6MwPCCR936cYfM1dLsGVnl",
            id: "6MwPCCR936cYfM1dLsGVnl",
            name: "Motionless In White",
            type: "artist",
            uri: "spotify:artist:6MwPCCR936cYfM1dLsGVnl",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 212082,
        explicit: false,
        external_ids: {
          isrc: "NLA322200044",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/1e1rQNYCZToyBDDka1Io34",
        },
        href: "https://api.spotify.com/v1/tracks/1e1rQNYCZToyBDDka1Io34",
        id: "1e1rQNYCZToyBDDka1Io34",
        is_local: false,
        name: "Werewolf",
        popularity: 62,
        preview_url:
          "https://p.scdn.co/mp3-preview/3b15202124131c1db28f68df476ad90498c45250?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 3,
        type: "track",
        uri: "spotify:track:1e1rQNYCZToyBDDka1Io34",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3mY9Ii0cL5SQxpOTAm8SHx",
              },
              href: "https://api.spotify.com/v1/artists/3mY9Ii0cL5SQxpOTAm8SHx",
              id: "3mY9Ii0cL5SQxpOTAm8SHx",
              name: "Warren Zevon",
              type: "artist",
              uri: "spotify:artist:3mY9Ii0cL5SQxpOTAm8SHx",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/03WJAI8NnJHvCNqnlLw8kg",
          },
          href: "https://api.spotify.com/v1/albums/03WJAI8NnJHvCNqnlLw8kg",
          id: "03WJAI8NnJHvCNqnlLw8kg",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273d6355fe477e861be56ad0eac",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02d6355fe477e861be56ad0eac",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851d6355fe477e861be56ad0eac",
              width: 64,
            },
          ],
          name: "Excitable Boy",
          release_date: "1978-06-01",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:03WJAI8NnJHvCNqnlLw8kg",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3mY9Ii0cL5SQxpOTAm8SHx",
            },
            href: "https://api.spotify.com/v1/artists/3mY9Ii0cL5SQxpOTAm8SHx",
            id: "3mY9Ii0cL5SQxpOTAm8SHx",
            name: "Warren Zevon",
            type: "artist",
            uri: "spotify:artist:3mY9Ii0cL5SQxpOTAm8SHx",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 209466,
        explicit: false,
        external_ids: {
          isrc: "USEE10610109",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/6kotXaSQaGYxE62hVpdHWu",
        },
        href: "https://api.spotify.com/v1/tracks/6kotXaSQaGYxE62hVpdHWu",
        id: "6kotXaSQaGYxE62hVpdHWu",
        is_local: false,
        name: "Werewolves of London",
        popularity: 60,
        preview_url:
          "https://p.scdn.co/mp3-preview/197ff6ed11285f1ae32e1e4bb0e484933a14ec2c?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 4,
        type: "track",
        uri: "spotify:track:6kotXaSQaGYxE62hVpdHWu",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3g2kUQ6tHLLbmkV7T4GPtL",
              },
              href: "https://api.spotify.com/v1/artists/3g2kUQ6tHLLbmkV7T4GPtL",
              id: "3g2kUQ6tHLLbmkV7T4GPtL",
              name: "Fiona Apple",
              type: "artist",
              uri: "spotify:artist:3g2kUQ6tHLLbmkV7T4GPtL",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6B5favhKTShFTjRLsKIUfa",
          },
          href: "https://api.spotify.com/v1/albums/6B5favhKTShFTjRLsKIUfa",
          id: "6B5favhKTShFTjRLsKIUfa",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2731443bd487a471868735f050b",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e021443bd487a471868735f050b",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048511443bd487a471868735f050b",
              width: 64,
            },
          ],
          name: "The Idler Wheel Is Wiser Than the Driver of the Screw and Whipping Cords Will Serve You More Than Ropes Will Ever Do (Expanded Edition)",
          release_date: "2012-06-18",
          release_date_precision: "day",
          total_tracks: 11,
          type: "album",
          uri: "spotify:album:6B5favhKTShFTjRLsKIUfa",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3g2kUQ6tHLLbmkV7T4GPtL",
            },
            href: "https://api.spotify.com/v1/artists/3g2kUQ6tHLLbmkV7T4GPtL",
            id: "3g2kUQ6tHLLbmkV7T4GPtL",
            name: "Fiona Apple",
            type: "artist",
            uri: "spotify:artist:3g2kUQ6tHLLbmkV7T4GPtL",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 192706,
        explicit: false,
        external_ids: {
          isrc: "USSM11202382",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5exHP9IYyaFSeQ5Y4OtbKb",
        },
        href: "https://api.spotify.com/v1/tracks/5exHP9IYyaFSeQ5Y4OtbKb",
        id: "5exHP9IYyaFSeQ5Y4OtbKb",
        is_local: false,
        name: "Werewolf",
        popularity: 41,
        preview_url:
          "https://p.scdn.co/mp3-preview/f037453007185017dc4a2d4a4d2687912c83d275?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 6,
        type: "track",
        uri: "spotify:track:5exHP9IYyaFSeQ5Y4OtbKb",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4lYtGx5NZQJHsMyhHc5iz3",
              },
              href: "https://api.spotify.com/v1/artists/4lYtGx5NZQJHsMyhHc5iz3",
              id: "4lYtGx5NZQJHsMyhHc5iz3",
              name: "The Cramps",
              type: "artist",
              uri: "spotify:artist:4lYtGx5NZQJHsMyhHc5iz3",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6S9rbimtTmC0v6UBWqSpay",
          },
          href: "https://api.spotify.com/v1/albums/6S9rbimtTmC0v6UBWqSpay",
          id: "6S9rbimtTmC0v6UBWqSpay",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273d2c32a4c277f8cd46f89f700",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02d2c32a4c277f8cd46f89f700",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851d2c32a4c277f8cd46f89f700",
              width: 64,
            },
          ],
          name: "Songs The Lord Taught Us",
          release_date: "1980",
          release_date_precision: "year",
          total_tracks: 18,
          type: "album",
          uri: "spotify:album:6S9rbimtTmC0v6UBWqSpay",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4lYtGx5NZQJHsMyhHc5iz3",
            },
            href: "https://api.spotify.com/v1/artists/4lYtGx5NZQJHsMyhHc5iz3",
            id: "4lYtGx5NZQJHsMyhHc5iz3",
            name: "The Cramps",
            type: "artist",
            uri: "spotify:artist:4lYtGx5NZQJHsMyhHc5iz3",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 183866,
        explicit: false,
        external_ids: {
          isrc: "USIR38900032",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/3sEQf5AuiphddGXRIWBcO9",
        },
        href: "https://api.spotify.com/v1/tracks/3sEQf5AuiphddGXRIWBcO9",
        id: "3sEQf5AuiphddGXRIWBcO9",
        is_local: false,
        name: "I Was A Teenage Werewolf - Remastered",
        popularity: 53,
        preview_url:
          "https://p.scdn.co/mp3-preview/3e00ffb93602d37a82022451f6b1a03d51b6477c?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 4,
        type: "track",
        uri: "spotify:track:3sEQf5AuiphddGXRIWBcO9",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/69udE1SS0NDUtbx6HKiO4r",
              },
              href: "https://api.spotify.com/v1/artists/69udE1SS0NDUtbx6HKiO4r",
              id: "69udE1SS0NDUtbx6HKiO4r",
              name: "Jeff Richmond",
              type: "artist",
              uri: "spotify:artist:69udE1SS0NDUtbx6HKiO4r",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6rcW0B3FqEjG6h0V3sSZ7O",
          },
          href: "https://api.spotify.com/v1/albums/6rcW0B3FqEjG6h0V3sSZ7O",
          id: "6rcW0B3FqEjG6h0V3sSZ7O",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2737ef5d624d6987e469d355b79",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e027ef5d624d6987e469d355b79",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048517ef5d624d6987e469d355b79",
              width: 64,
            },
          ],
          name: "30 Rock",
          release_date: "2010-01-01",
          release_date_precision: "day",
          total_tracks: 31,
          type: "album",
          uri: "spotify:album:6rcW0B3FqEjG6h0V3sSZ7O",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/69udE1SS0NDUtbx6HKiO4r",
            },
            href: "https://api.spotify.com/v1/artists/69udE1SS0NDUtbx6HKiO4r",
            id: "69udE1SS0NDUtbx6HKiO4r",
            name: "Jeff Richmond",
            type: "artist",
            uri: "spotify:artist:69udE1SS0NDUtbx6HKiO4r",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0W7nWv2YrpKKwsTJPWgJ8L",
            },
            href: "https://api.spotify.com/v1/artists/0W7nWv2YrpKKwsTJPWgJ8L",
            id: "0W7nWv2YrpKKwsTJPWgJ8L",
            name: "Tracy Morgan",
            type: "artist",
            uri: "spotify:artist:0W7nWv2YrpKKwsTJPWgJ8L",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 172733,
        explicit: false,
        external_ids: {
          isrc: "US6LQ0900179",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/1QUXgI2yyMTx88kwQ8dA8Y",
        },
        href: "https://api.spotify.com/v1/tracks/1QUXgI2yyMTx88kwQ8dA8Y",
        id: "1QUXgI2yyMTx88kwQ8dA8Y",
        is_local: false,
        name: "Werewolf Bar Mitzvah",
        popularity: 24,
        preview_url:
          "https://p.scdn.co/mp3-preview/c4732de844c23b60643019a194850d9ed674b1fa?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 21,
        type: "track",
        uri: "spotify:track:1QUXgI2yyMTx88kwQ8dA8Y",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3ApUX1o6oSz321MMECyIYd",
              },
              href: "https://api.spotify.com/v1/artists/3ApUX1o6oSz321MMECyIYd",
              id: "3ApUX1o6oSz321MMECyIYd",
              name: "Quinn XCII",
              type: "artist",
              uri: "spotify:artist:3ApUX1o6oSz321MMECyIYd",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/7zGPSFi3LOIC1L5Dj0oEBx",
          },
          href: "https://api.spotify.com/v1/albums/7zGPSFi3LOIC1L5Dj0oEBx",
          id: "7zGPSFi3LOIC1L5Dj0oEBx",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27371240fd7447ba7f20c5600ec",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0271240fd7447ba7f20c5600ec",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485171240fd7447ba7f20c5600ec",
              width: 64,
            },
          ],
          name: "From Michigan With Love",
          release_date: "2019-02-15",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:7zGPSFi3LOIC1L5Dj0oEBx",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3ApUX1o6oSz321MMECyIYd",
            },
            href: "https://api.spotify.com/v1/artists/3ApUX1o6oSz321MMECyIYd",
            id: "3ApUX1o6oSz321MMECyIYd",
            name: "Quinn XCII",
            type: "artist",
            uri: "spotify:artist:3ApUX1o6oSz321MMECyIYd",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0rAt7V95LWbRPvWQFd21il",
            },
            href: "https://api.spotify.com/v1/artists/0rAt7V95LWbRPvWQFd21il",
            id: "0rAt7V95LWbRPvWQFd21il",
            name: "Yoshi Flower",
            type: "artist",
            uri: "spotify:artist:0rAt7V95LWbRPvWQFd21il",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 191893,
        explicit: false,
        external_ids: {
          isrc: "USSM11807843",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5foPGlyY3O4uSrFGhfUKGW",
        },
        href: "https://api.spotify.com/v1/tracks/5foPGlyY3O4uSrFGhfUKGW",
        id: "5foPGlyY3O4uSrFGhfUKGW",
        is_local: false,
        name: "Werewolf (feat. Yoshi Flower)",
        popularity: 41,
        preview_url:
          "https://p.scdn.co/mp3-preview/5b6f699ca43967c18d03cbe664cf88029c138597?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 5,
        type: "track",
        uri: "spotify:track:5foPGlyY3O4uSrFGhfUKGW",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2sG4zTOLvjKG1PSoOyf5Ej",
              },
              href: "https://api.spotify.com/v1/artists/2sG4zTOLvjKG1PSoOyf5Ej",
              id: "2sG4zTOLvjKG1PSoOyf5Ej",
              name: "Brandi Carlile",
              type: "artist",
              uri: "spotify:artist:2sG4zTOLvjKG1PSoOyf5Ej",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5mIT7iw9w64DMP2vxP9L1f",
          },
          href: "https://api.spotify.com/v1/albums/5mIT7iw9w64DMP2vxP9L1f",
          id: "5mIT7iw9w64DMP2vxP9L1f",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27335bd3c588974a8c239e5de87",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0235bd3c588974a8c239e5de87",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485135bd3c588974a8c239e5de87",
              width: 64,
            },
          ],
          name: "In These Silent Days",
          release_date: "2021-10-01",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:5mIT7iw9w64DMP2vxP9L1f",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2sG4zTOLvjKG1PSoOyf5Ej",
            },
            href: "https://api.spotify.com/v1/artists/2sG4zTOLvjKG1PSoOyf5Ej",
            id: "2sG4zTOLvjKG1PSoOyf5Ej",
            name: "Brandi Carlile",
            type: "artist",
            uri: "spotify:artist:2sG4zTOLvjKG1PSoOyf5Ej",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 221813,
        explicit: false,
        external_ids: {
          isrc: "USAT22102160",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/3prWmTfS6HnvkKgezSQFJO",
        },
        href: "https://api.spotify.com/v1/tracks/3prWmTfS6HnvkKgezSQFJO",
        id: "3prWmTfS6HnvkKgezSQFJO",
        is_local: false,
        name: "Mama Werewolf",
        popularity: 47,
        preview_url:
          "https://p.scdn.co/mp3-preview/2a7bb55bdcbbed1df17aa10b437f70ca17791124?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 6,
        type: "track",
        uri: "spotify:track:3prWmTfS6HnvkKgezSQFJO",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/05fo024EFotg9songSENOZ",
              },
              href: "https://api.spotify.com/v1/artists/05fo024EFotg9songSENOZ",
              id: "05fo024EFotg9songSENOZ",
              name: "CocoRosie",
              type: "artist",
              uri: "spotify:artist:05fo024EFotg9songSENOZ",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5fOoRaRwqNW9aoCgZ7L0ll",
          },
          href: "https://api.spotify.com/v1/albums/5fOoRaRwqNW9aoCgZ7L0ll",
          id: "5fOoRaRwqNW9aoCgZ7L0ll",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27382139fe8ad2a09b7d8a1ce0d",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0282139fe8ad2a09b7d8a1ce0d",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485182139fe8ad2a09b7d8a1ce0d",
              width: 64,
            },
          ],
          name: "The Adventures of Ghosthorse & Stillborn",
          release_date: "2007-04-10",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:5fOoRaRwqNW9aoCgZ7L0ll",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/05fo024EFotg9songSENOZ",
            },
            href: "https://api.spotify.com/v1/artists/05fo024EFotg9songSENOZ",
            id: "05fo024EFotg9songSENOZ",
            name: "CocoRosie",
            type: "artist",
            uri: "spotify:artist:05fo024EFotg9songSENOZ",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 290186,
        explicit: false,
        external_ids: {
          isrc: "USTG30730607",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/1RgFmvtcKaMHHRtx1qrtM5",
        },
        href: "https://api.spotify.com/v1/tracks/1RgFmvtcKaMHHRtx1qrtM5",
        id: "1RgFmvtcKaMHHRtx1qrtM5",
        is_local: false,
        name: "Werewolf",
        popularity: 37,
        preview_url:
          "https://p.scdn.co/mp3-preview/c062145d5bf0a1ec6997bb633993f869513b3fe2?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 7,
        type: "track",
        uri: "spotify:track:1RgFmvtcKaMHHRtx1qrtM5",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/0o7WWONtleH6PWLn5GIoCM",
              },
              href: "https://api.spotify.com/v1/artists/0o7WWONtleH6PWLn5GIoCM",
              id: "0o7WWONtleH6PWLn5GIoCM",
              name: "Every Time I Die",
              type: "artist",
              uri: "spotify:artist:0o7WWONtleH6PWLn5GIoCM",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6Bl4e9l92OjIZIGYMVR4AN",
          },
          href: "https://api.spotify.com/v1/albums/6Bl4e9l92OjIZIGYMVR4AN",
          id: "6Bl4e9l92OjIZIGYMVR4AN",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273b20b4eda092b1f26bede8d35",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02b20b4eda092b1f26bede8d35",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851b20b4eda092b1f26bede8d35",
              width: 64,
            },
          ],
          name: "The Big Dirty",
          release_date: "2007-09-04",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:6Bl4e9l92OjIZIGYMVR4AN",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0o7WWONtleH6PWLn5GIoCM",
            },
            href: "https://api.spotify.com/v1/artists/0o7WWONtleH6PWLn5GIoCM",
            id: "0o7WWONtleH6PWLn5GIoCM",
            name: "Every Time I Die",
            type: "artist",
            uri: "spotify:artist:0o7WWONtleH6PWLn5GIoCM",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 204720,
        explicit: false,
        external_ids: {
          isrc: "US3H40708504",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5Bfy6Wfj4G1GBYWlMfQ1by",
        },
        href: "https://api.spotify.com/v1/tracks/5Bfy6Wfj4G1GBYWlMfQ1by",
        id: "5Bfy6Wfj4G1GBYWlMfQ1by",
        is_local: false,
        name: "We'rewolf",
        popularity: 36,
        preview_url:
          "https://p.scdn.co/mp3-preview/99533ca5e55e4f507dc883a0c3b21e10475adaf7?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 4,
        type: "track",
        uri: "spotify:track:5Bfy6Wfj4G1GBYWlMfQ1by",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2yDodJUwXfdHzg4crwslUp",
              },
              href: "https://api.spotify.com/v1/artists/2yDodJUwXfdHzg4crwslUp",
              id: "2yDodJUwXfdHzg4crwslUp",
              name: "Allah-Las",
              type: "artist",
              uri: "spotify:artist:2yDodJUwXfdHzg4crwslUp",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4fE2s88EMMyrZDHu5HFluy",
          },
          href: "https://api.spotify.com/v1/albums/4fE2s88EMMyrZDHu5HFluy",
          id: "4fE2s88EMMyrZDHu5HFluy",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27317fbd53c45afa1a90846aa28",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0217fbd53c45afa1a90846aa28",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485117fbd53c45afa1a90846aa28",
              width: 64,
            },
          ],
          name: "Worship the Sun",
          release_date: "2014-09-15",
          release_date_precision: "day",
          total_tracks: 14,
          type: "album",
          uri: "spotify:album:4fE2s88EMMyrZDHu5HFluy",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2yDodJUwXfdHzg4crwslUp",
            },
            href: "https://api.spotify.com/v1/artists/2yDodJUwXfdHzg4crwslUp",
            id: "2yDodJUwXfdHzg4crwslUp",
            name: "Allah-Las",
            type: "artist",
            uri: "spotify:artist:2yDodJUwXfdHzg4crwslUp",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 148026,
        explicit: false,
        external_ids: {
          isrc: "USD8D1418013",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5wpxEEtz1BuF0a36Rf1k5T",
        },
        href: "https://api.spotify.com/v1/tracks/5wpxEEtz1BuF0a36Rf1k5T",
        id: "5wpxEEtz1BuF0a36Rf1k5T",
        is_local: false,
        name: "No Werewolf",
        popularity: 49,
        preview_url:
          "https://p.scdn.co/mp3-preview/686a3666484254b1c13dbbee3149ad4383270781?cid=e9b1abef9cd84cecb883434c4d6de44b",
        track_number: 13,
        type: "track",
        uri: "spotify:track:5wpxEEtz1BuF0a36Rf1k5T",
      },
    ],
    limit: 10,
    next: "https://api.spotify.com/v1/search?query=werewolf&type=track&offset=10&limit=10",
    offset: 0,
    previous: null,
    total: 1000,
  },
};
